config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :acorn_hashtags
  resources :hashtags
  resources :likes
  resources :acorns
  resources :follows
  resources :users, except: [:new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "acorns#index"
  get "/sign-up", to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/likes', to: "likes#new"
  delete '/logout', to: 'sessions#destroy'
  post '/acorns/new', to: 'acorns#create'
  delete '/likes', to: 'likes#destroy'
  get '/explore', to: 'pages#explore'
  
end

app/models/user.rb
class User < ApplicationRecord

    validates :username, :email, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
    validates :email, format:
     {with: URI::MailTo::EMAIL_REGEXP}
    validates :password, presence: true
    has_secure_password

    

    has_many :likes
    has_many :acorns
    
    has_many :follower_relationships, foreign_key: :followed_id, class_name: 'Follow'
    has_many :followers, through: :follower_relationships, source: :follower
  
    has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
    has_many :following, through: :following_relationships, source: :followed

    def image_path_exists
        require 'open-uri'
        # is the url valid?
        # does the response have a content type img

        begin
            # if thrown an exception, then rescue will execute
            path = URI.open(:profile_img)

            errors.add(:image_path, "URL does not contain image") and return unless path.content_type.starts_with?("image")
        rescue 
            errors.add(:profile_img, "Invalid URL")
            
        end

       
        
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :already_signed_in?, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
       
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :bio, :profile_img)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="center-form">

<div class="new-form">

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div>
    <%= form.label :username, style: "display: block;" %>
    <%= form.text_field :username,  style: "display: block; border-radius: 9999px" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block;" %>
    <%= form.text_field :email, style: "display: block; border-radius: 9999px" %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password, style: "display: block; border-radius: 9999px" %>
  </div>


  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_field :bio, style: "display: block; border-radius: 9999px" %>
  </div>

  <div style="margin-top: .5em;", >
    <%= form.submit "Sign Up", class: "border-0 fs-4 extra-round button-style wide" %>
  </div>

  </div>
<% end %>

</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
 <%= image_tag url_for(user.profile_img), class: "profile-img" ,
            alt: "#{user.username}'s profile photo " %>
<b><p>
@ <%= @user.username %>
</b></p>

  <p>

    <%= @user.bio %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<style>

  
  .center-form {
    display: flex;
    justify-content: center;
   
    height: 100vh;
  }
  

  .new-form {
    width: 200px;
    height: 200px;
    border-color: black;
    border: 5px;
    
  }

</style>


<div class="center-form">

<div class="new-form">
<h3>New user</h3>


<%= render "form", user: @user %>

</div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>



<%= render @user %>


<% if current_user != nil && !Follow.find_by(follower_id: current_user.id, followed_id: @user.id) %>
        <%= button_to "Follow", follows_path, method: :post, params: { follow: {follower_id: current_user.id, followed_id: @user.id }} %>


<% end %>




<% if Follow.find_by(follower_id: current_user.id, followed_id: @user.id) %>
<%= button_to "UnFollow", Follow.find_by(follower_id: current_user.id, followed_id: @user.id), method: :delete %>
<% end %>

<h5 class="mt-4"> Followers:
 </h5>
 
         <% @user.followers.each do |follower|%>
         
          <p>@<%= follower.username %></p>
        <% end %>
  
  
  
  
     <% if current_user != nil && @user.id == current_user.id %>
  <div class="mt-4 mb-4">
  <%= link_to "Edit Profile", edit_user_path(@user) %>


  <%# <%= button_to "Delete account", @user, method: :delete %>
</div>

<% end %>

<% Acorn.where(user_id: @user.id).each do |acorn| %>

  <%= render acorn %>

  <% end %>