config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :acorn_hashtags
  resources :hashtags
  resources :likes
  resources :acorns
  resources :follows
  resources :users, except: [:new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "acorns#index"
  get "/sign-up", to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/likes', to: "likes#new"
  delete '/logout', to: 'sessions#destroy'
  post '/acorns/new', to: 'acorns#create'
  delete '/likes', to: 'likes#destroy'
  get '/explore', to: 'pages#explore'
  
end

app/models/acorn.rb
class Acorn < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: {minimum: 2, mexium: 100}
  
  has_many :likes
  has_many :replies
  has_many :acorn_hastags
  

  has_many :acorns, :through => :replies

  has_many :hastags, :through => :acorn_hastags

end

app/models/acorn_hashtag.rb
class AcornHashtag < ApplicationRecord
  belongs_to :acorn
  belongs_to :hastag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord
    validates :follower_id, uniqueness: { scope: :followed_id }
    belongs_to :follower, class_name: 'User'
    belongs_to :followed, class_name: 'User'
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :acorn_id }
  belongs_to :acorn
  belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :acorn
  belongs_to :acorn
end

app/models/user.rb
class User < ApplicationRecord

    validates :username, :email, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
    validates :email, format:
     {with: URI::MailTo::EMAIL_REGEXP}
    validates :password, presence: true
    has_secure_password

    

    has_many :likes
    has_many :acorns
    
    has_many :follower_relationships, foreign_key: :followed_id, class_name: 'Follow'
    has_many :followers, through: :follower_relationships, source: :follower
  
    has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
    has_many :following, through: :following_relationships, source: :followed

    def image_path_exists
        require 'open-uri'
        # is the url valid?
        # does the response have a content type img

        begin
            # if thrown an exception, then rescue will execute
            path = URI.open(:profile_img)

            errors.add(:image_path, "URL does not contain image") and return unless path.content_type.starts_with?("image")
        rescue 
            errors.add(:profile_img, "Invalid URL")
            
        end

       
        
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[ show edit update destroy ]
  before_action :require_user

  # GET /likes or /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1 or /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
      
   
    
      else
        flash[:notice] = @like.errors.full_messages.to_sentence
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1 or /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to like_url(@like), notice: "Like was successfully updated." }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    @like.destroy


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:acorn_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @acorns = Acorn.order(date_created: :desc)
    end 

    def explore
        @acorns = Acorn.all.sample(20)
    end

    def following

        current_user.followers.each do |follower|
         
            follower.acorns.all.each do |acorn|


            end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :already_signed_in?, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
       
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :bio, :profile_img)
    end
end

app/helpers/acorns_helper.rb
module AcornsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
      if session != nil
      User.find(session[:user_id])  if session[:user_id]
      end
    end

    def logged_in?
        !!current_user
    end


end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OakTree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag "favicon.ico" %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <link rel="icon" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,600,1,0" />

    <link href="https://fonts.googleapis.com/css?family=Asap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />


  </head>

  <body>
  <div class="wrapper">
  <div class="main-content">
<div class="left-col border border-0">
  <%= render partial: "pages/left_nav" %>
</div>
  <div class="middle-col">
  <%= render partial: "pages/top_new" %>
   <%= yield %>
</div>
<% if current_user != nil %>
<div class="right-col border border-1">
  <%= render partial: "pages/right_nav" %>
</div>
<% end %>
  </div>
  </div>
   
  </body>
</html>

app/views/pages/_acorn_display.html.erb
  <% @acorns.each do |acorn| %>
    <div class="acorn-wrapper ">
      <div class="acorn-header">
          <%= image_tag url_ for(acorn.user.profile_img), class: "profile-img",
            alt: "#{acorn.user.username}'s profile photo " %>
        
        <div class="acorn-user-info">
            <b>
              @<%= acorn.user.username %>
            </b>
          <%= acorn.date_created.strftime("%m-%d-%Y") %>
    <p><%= acorn.content %></p>
        </div>
      </div>

      <%# if acorn has an image do this  %>

       <div class="acorn-footer">
    
    <div class="comments">
      
      <svg class="feather feather-message-circle sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
      <div class="comment-count">33</div>
    </div>
    
    <div class="retweets">
      <svg class="feather feather-repeat sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="17 1 21 5 17 9"></polyline><path d="M3 11V9a4 4 0 0 1 4-4h14"></path><polyline points="7 23 3 19 7 15"></polyline><path d="M21 13v2a4 4 0 0 1-4 4H3"></path></svg>
      <div class="retweet-count">397</div>
    </div>
    
    <div class="likes">
      <svg class="feather feather-heart sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
      <div class="likes-count">
        2.6k
      </div>
    </div>
    
    <div class="message">
      <svg class="feather feather-send sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>
    </div>
  </div>

    </div>
    <% end %>

app/views/pages/_followers.html.erb
<% user = User.find(1) %>
    <% user.followers.each do |followers| %>
    <%= followers.username %>
    <% end %>

app/views/pages/_following.html.erb
<% user = User.find(1) %>
    <% user.following.each do |following| %>
    <%= following.username %>
    <% end %>

app/views/pages/_left_nav.html.erb
<ul class="list-group">
  <li class="border-0 fs-4"> <span class="material-symbols-outlined tree p-3 mb-1">
nature
</span>Oak_Tree</li>
  <li></li>
   <% if logged_in? == false %>
    <%= link_to sign_up_path do %>
     <li><button type="button" class="border-0 fs-4 extra-round button-style wide">Sign Up</button></li>
     <% end %>
  <%= link_to login_path do %>
   <li><button type="button" class="border-0 fs-4 extra-round button-style wide">Login</button></li>
   <% end %>
   <% end %>

    <%= link_to root_path	do %><li class="list-group-item border-0 fs-4"><i class="fa-solid fa-house p-3 "></i>Home</li></a>
    <% end %>
    <%# <%= link_to explore_path do %>
    <%# <li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-hashtag p-3"></i>Explore</li> </a> %>
    <%# <% end %>

    <% if logged_in? %>
    <a href="#"><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-regular fa-bell p-3"></i>Notifications</li></a>
    <a href="#"><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-message p-3"></i>Messages</li></a>
     <%= link_to url_for(controller: "users", action: "show", id: session[:user_id]) do %><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-user-secret p-3"></i>Profile</li></a>
     <% end %>
    <a href="#" class="rounded-lg"><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-ellipsis p-3"></i>More</li></a>
    <li></li>


    <%= link_to new_acorn_path do %>
    <li><button type="button" class="border-0 fs-4 extra-round button-style wide">Acorn</button></li>
    <% end %>
     <%= link_to logout_path, data: {"turbo-method": :delete} do %>
   <li><center><p class="fs-6 mt-3" >Log out</p></center></li>
   <% end %>
    <% end %>


    <% if logged_in? %>
    <div class="user-profile-nav">
     <div class="acorn-header">
        <%= link_to current_user do%>
          <%= image_tag url_for(current_user.profile_img), class: "profile-img" ,
            alt: "#{current_user.username}'s profile photo " %>
        
        <div class="acorn-user-info">
            <b>
              @<%= link_to current_user.username, user_path(current_user) %>
            </b>
            </div>
            <% end %>

            </div>
            </div>
            <% end %>

  </ul>

app/views/pages/_profile.html.erb
 <%= link_to follows_path do %><li class="list-group-item border-0 fs-4"><i class="fa-solid fa-house p-3 "></i>Followers</li></a>
    <% end %>

app/views/pages/_right_nav.html.erb
<h3> Recomended Users: </h3>

<% @users = User.all.sample(5) %>
<div class="display-flex-column">
<% @users.each do |user| %>

  
    <%= link_to user do%>
          <%= image_tag url_for(user.profile_img), class: "profile-img" ,
            alt: "#{user.username}'s profile photo " %>
        
        <div class="acorn-user-info">
            <b>
              @<%= link_to user.username, user_path(user) %>
            </b>
            <% end %>
          

<hr>
<% end %>
</div>

app/views/pages/_top_new.html.erb
<div class="top-sticky">
<div class="search-bar-container">
<form class="form-inline my-2 my-lg-0 ml-auto search-bar extra-round">
       <%= form_tag(acorns_path, method: :get) do %>
<div class="input-group">
  <%= text_field_tag :q, nil, class: "form-control extra-round-bar"  %>
   <div class="input-group-append">
  <%= submit_tag("Search", class: "btn btn-light mx-2 extra-round") %>
   </div>
        </div>
<% end %>
      </form>
</div>

<div class="top-new">
<ul>
<%= link_to root_path(@acorn, q: "Top") do %>
<li><b>Top</b></li>
<% end %>
<%= link_to root_path(@acorn, q: "New") do %>
<li><b>New</b></li>
<% end %>
</ul>
</div>
</div>

app/views/pages/explore.html.erb
<% @acorns.each do |acorn| %>
   
      <%= render acorn, locals: {query: params[:q]} %>
    
    <% end %>

    

   

app/views/pages/following.html.erb
 <% current_user.followers.each do |follower|%>
         
          <p><%= render follower.acorns.all %></p>
        <% end %>

app/views/pages/index.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />


<%# <nav class="navbar navbar-expand-lg navbar-dark  sticky-top">
  <div class="container">
   
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      
    </div>
  </div>
</nav> %>



<div class="wrapper">
  <div class="main-content">
<div class="left-col border border-0">
  <%= render partial: "shared/left_nav", locals: { acorns: @acorns } %>
</div>
  <div class="middle-col">
  <%= render partial: "shared/top_new" %>
  <%= render partial: "shared/acorn_display" %>
</div>
<div class="right-col border border-1">
  <%= render partial: "shared/right_nav" %>
</div>

  </div>
  </div>

app/views/shared/_acorn_display.html.erb
  <% @acorns.each do |acorn| %>
    <div class="acorn-wrapper ">
      <div class="acorn-header">
          <%= image_tag url_for(acorn.user.profile_img), class: "profile-img",
            alt: "#{acorn.user.username}'s profile photo " %>
        
        <div class="acorn-user-info">
            <b>
              @<%= acorn.user.username %>
            </b>
          <%= acorn.date_created.strftime("%m-%d-%Y") %>
    <p><%= acorn.content %></p>
        </div>
      </div>

      <%# if acorn has an image do this  %>

       <div class="acorn-footer">
    
    <div class="comments">
      
      <svg class="feather feather-message-circle sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
      <div class="comment-count">33</div>
    </div>
    
    <div class="retweets">
      <svg class="feather feather-repeat sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="17 1 21 5 17 9"></polyline><path d="M3 11V9a4 4 0 0 1 4-4h14"></path><polyline points="7 23 3 19 7 15"></polyline><path d="M21 13v2a4 4 0 0 1-4 4H3"></path></svg>
      <div class="retweet-count">397</div>
    </div>
    
    <div class="likes">
      <svg class="feather feather-heart sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
      <div class="likes-count">
        2.6k
      </div>
    </div>
    
    <div class="message">
      <svg class="feather feather-send sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>
    </div>
  </div>

    </div>
    <% end %>

app/views/shared/_left_nav.html.erb
<ul class="list-group">
  <li class="border-0 fs-4"> <span class="material-symbols-outlined tree p-3 mb-1">
nature
</span>Oak_Tree</li>
  <li></li>
   <%# <% if !user_signed_in? %>
    <%= link_to sign_up_path do %>
     <li><button type="button" class="border-0 fs-4 extra-round button-style wide">Sign Up</button></li>
     <% end %>
  <%= link_to login_path do %>
   <li><button type="button" class="border-0 fs-4 extra-round button-style wide">Login</button></li>
   <% end %>

    <%= link_to root_path	do %><li class="list-group-item border-0 fs-4"><i class="fa-solid fa-house p-3 "></i>Home</li></a>
    <% end %>
    <a href="#"><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-hashtag p-3"></i>Explore</li> </a>

    <%# <% if user_signed_in? %>
    <a href="#"><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-regular fa-bell p-3"></i>Notifications</li></a>
    <a href="#"><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-message p-3"></i>Messages</li></a>
     <%= link_to url_for(controller: "users", action: "show", id: 1) do %><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-user-secret p-3"></i>Profile</li></a>
     <% end %>
    <a href="#" class="rounded-lg"><li class="list-group-item border-0 fs-4 rounded-lg"><i class="fa-solid fa-ellipsis p-3"></i>More</li></a>
    <li></li>


    <%= link_to new_acorn_path do %>
    <li><button type="button" class="border-0 fs-4 extra-round button-style wide">Acorn</button></li>
    <%# <% end %>
    <% end %>
  </ul>