config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :acorn_hashtags
  resources :hashtags
  resources :likes
  resources :acorns
  resources :follows
  resources :users, except: [:new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "acorns#index"
  get "/sign-up", to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/likes', to: "likes#new"
  delete '/logout', to: 'sessions#destroy'
  post '/acorns/new', to: 'acorns#create'
  delete '/likes', to: 'likes#destroy'
  get '/explore', to: 'pages#explore'
  
end

app/models/acorn.rb
class Acorn < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: {minimum: 2, mexium: 100}
  
  has_many :likes
  has_many :replies
  has_many :acorn_hastags
  

  has_many :acorns, :through => :replies

  has_many :hastags, :through => :acorn_hastags

end

app/controllers/acorns_controller.rb
class AcornsController < ApplicationController
  before_action :set_acorn, only: %i[ show edit update destroy ]


  # GET /acorns or /acorns.json
  def index
    @query = params[:q]
    if @query == "New"
      @acorns = Acorn.order(created_at: :desc)
      paginate
    elsif @query
      @acorns = Acorn.where("content LIKE ?", "%#{params[:q]}%")
      paginate
    else
      @acorns = Acorn.all
      paginate
     
    end
  end

  def paginate
    @per_page = 10
    @page = (params[:page] || 1).to_i
    @total_count = @acorns.count
    @total_pages = (@total_count / @per_page.to_f).ceil
    @acorns = @acorns.offset((@page - 1) * @per_page).limit(@per_page)
  end

  # GET /acorns/1 or /acorns/1.json
  def show
  end

  # GET /acorns/new
  def new
    @acorn = Acorn.new
  end

  # GET /acorns/1/edit
  def edit
  end

  # POST /acorns or /acorns.json
  def create
    @acorn = helpers.current_user.acorns.new(acorn_params)

    respond_to do |format|
      if @acorn.save
        flash[:notice] = "works!"
        format.html { redirect_to acorn_url(@acorn), notice: "Acorn was successfully created." }
        format.json { render :show, status: :created, location: @acorn }
      else
        flash[:notice] = "lol failed."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @acorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acorns/1 or /acorns/1.json
  def update
    respond_to do |format|
      if @acorn.update(acorn_params)
        format.html { redirect_to root_path, notice: "Acorn was successfully updated." }
        format.json { render :show, status: :ok, location: @acorn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @acorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acorns/1 or /acorns/1.json
  def destroy
    @acorn.destroy

    respond_to do |format|
      format.html { redirect_to acorns_url, notice: "Acorn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_acorn
    @acorn = Acorn.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def acorn_params
    params.require(:acorn).permit(:content, :date_created, :img, :link, :reply, :user_id)
  end
end

app/helpers/acorns_helper.rb
module AcornsHelper
end

app/views/acorns/_acorn.html.erb
<div class="acorn-wrapper ">
  <div class="acorn-header">
    <%= image_tag url_for(acorn.user.profile_img), class: "profile-img",
                                                         alt: "#{acorn.user.username}'s profile photo " %>
    <div class="acorn-user-info">
      <b>
        @<%= link_to acorn.user.username, user_path(acorn.user) %>
      </b>
      <%= link_to acorn do%>
        <%= acorn.created_at.strftime("%m-%d-%Y") %>
        <p><%= acorn.content %></p>
      <% end %>
    </div>
  </div>
    
    <div class="acorn-footer">
      <div class="comments">
        <svg class="feather feather-message-circle sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
        <div class="comment-count">33</div>
      </div>
      <div class="retweets">
        <svg class="feather feather-repeat sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="17 1 21 5 17 9"></polyline><path d="M3 11V9a4 4 0 0 1 4-4h14"></path><polyline points="7 23 3 19 7 15"></polyline><path d="M21 13v2a4 4 0 0 1-4 4H3"></path></svg>
        <div class="retweet-count">397</div>
      </div>
      <div class="likes">
        <% if current_user != nil && Like.find_by(user_id: current_user.id, acorn_id: acorn.id) %>
          <%= button_to Like.find_by(user_id: current_user.id, acorn_id: acorn.id), method: :delete, style: "border: 0px; padding-right: 0px; background-color: white;" do %>
            <svg class="feather feather-heart sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
          <% end %>
        <% end %>
        <% if current_user != nil && !Like.find_by(user_id: current_user.id, acorn_id: acorn.id) %>
          <form action="/likes" method="post">
            <input type="hidden" name="like[user_id]" value="<%= current_user.id %>">
            <input type="hidden" name="like[acorn_id]" value="<%= acorn.id %> ">
            <button style="border: 0px; padding-right: 0px; background-color: white;"> <svg class="feather feather-heart sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
            </button>
          </form>
        <% end %>
        <% if current_user == nil %>
          <svg class="feather feather-heart sc-dnqmqq jxshSx" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
        <% end %>
        <div class="likes-count">
          <%= acorn.likes.count %>
        </div>
        <% if current_user != nil && acorn.user_id == current_user.id %>
          <%= link_to edit_acorn_path(acorn) do %>
            <i class="fa-solid fa-pen-to-square p-1"></i>
          <% end %>
          <%= link_to acorn, data: {"turbo-method": :delete} do %>
            <i class="fa-solid fa-trash p-1"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  </div>

app/views/acorns/_form.html.erb
<%= form_with(model: acorn) do |form| %>
  <% if acorn.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(acorn.errors.count, "error") %> prohibited this acorn from being saved:</h2>

      <ul>
        <% acorn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
   <%= hidden_field_tag :date_created, Date.today %>
  </div>



  <div>
    
    <%= hidden_field_tag :reply %>
  </div>

 <%= hidden_field_tag :user_id, current_user %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/acorns/edit.html.erb
<h1>Editing acorn</h1>

<%= render "form", acorn: @acorn %>

<br>

<div>
  <%= link_to "Show this acorn", @acorn %> |
  <%= link_to "Back to acorns", acorns_path %>
</div>

app/views/acorns/index.html.erb
<% @acorns.each do |acorn| %>
   
      <%= render acorn,  locals: {query: params[:q]} %>
    
    <% end %>

    <% if @total_pages > 1 %>
    
  <nav class="text-center" style="width: 100%;>
    <ul class="pagination">
      <% if @page > 1 %>
        <li class="p-1 btn btn-sucess"><%= link_to 'Previous', acorns_path(page: @page - 1) %></li>
      <% end %>
      <% 1.upto(@total_pages) do |page| %>
        <li class="<%= 'active' if page == @page %> p-1  btn btn-sucess"><%= link_to page, acorns_path(page: page) %></li>
      <% end %>
      <% if @page < @total_pages %>
        <li class="p-1  btn btn-sucess"><%= link_to 'Next', acorns_path(page: @page + 1) %></li>
      <% end %>
    </ul>
  </nav>
 
<% end %>

app/views/acorns/new.html.erb
<h1>New acorn</h1>

<%= render "form", {acorn: @acorn} %>

<br>

app/views/acorns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @acorn %>

<% if current_user != nil && current_user == "#{@acorn.user_id}" %>
<div>
  <%= link_to "Edit this acorn", edit_acorn_path(@acorn) %> |
  <%= link_to "Back to acorns", acorns_path %>

  <%= button_to "Destroy this acorn", @acorn, method: :delete %>
</div>

<% end %>