config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :acorn_hashtags
  resources :hashtags
  resources :likes
  resources :acorns
  resources :follows
  resources :users, except: [:new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "acorns#index"
  get "/sign-up", to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/likes', to: "likes#new"
  delete '/logout', to: 'sessions#destroy'
  post '/acorns/new', to: 'acorns#create'
  delete '/likes', to: 'likes#destroy'
  get '/explore', to: 'pages#explore'
  
end

app/models/acorn_hashtag.rb
class AcornHashtag < ApplicationRecord
  belongs_to :acorn
  belongs_to :hastag
end

app/controllers/acorn_hashtags_controller.rb
class AcornHashtagsController < ApplicationController
  before_action :set_acorn_hashtag, only: %i[ show edit update destroy ]

  # GET /acorn_hashtags or /acorn_hashtags.json
  def index
    @acorn_hashtags = AcornHashtag.all
  end

  # GET /acorn_hashtags/1 or /acorn_hashtags/1.json
  def show
  end

  # GET /acorn_hashtags/new
  def new
    @acorn_hashtag = AcornHashtag.new
  end

  # GET /acorn_hashtags/1/edit
  def edit
  end

  # POST /acorn_hashtags or /acorn_hashtags.json
  def create
    @acorn_hashtag = AcornHashtag.new(acorn_hashtag_params)

    respond_to do |format|
      if @acorn_hashtag.save
        format.html { redirect_to acorn_hashtag_url(@acorn_hashtag), notice: "Acorn hashtag was successfully created." }
        format.json { render :show, status: :created, location: @acorn_hashtag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @acorn_hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acorn_hashtags/1 or /acorn_hashtags/1.json
  def update
    respond_to do |format|
      if @acorn_hashtag.update(acorn_hashtag_params)
        format.html { redirect_to acorn_hashtag_url(@acorn_hashtag), notice: "Acorn hashtag was successfully updated." }
        format.json { render :show, status: :ok, location: @acorn_hashtag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @acorn_hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acorn_hashtags/1 or /acorn_hashtags/1.json
  def destroy
    @acorn_hashtag.destroy

    respond_to do |format|
      format.html { redirect_to acorn_hashtags_url, notice: "Acorn hashtag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acorn_hashtag
      @acorn_hashtag = AcornHashtag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def acorn_hashtag_params
      params.require(:acorn_hashtag).permit(:acorn_id, :hastag_id)
    end
end

app/helpers/acorn_hashtags_helper.rb
module AcornHashtagsHelper
end

app/views/acorn_hashtags/_acorn_hashtag.html.erb
<div id="<%= dom_id acorn_hashtag %>">
  <p>
    <strong>Acorn:</strong>
    <%= acorn_hashtag.acorn_id %>
  </p>

  <p>
    <strong>Hastag:</strong>
    <%= acorn_hashtag.hastag_id %>
  </p>

</div>

app/views/acorn_hashtags/_form.html.erb
<%= form_with(model: acorn_hashtag) do |form| %>
  <% if acorn_hashtag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(acorn_hashtag.errors.count, "error") %> prohibited this acorn_hashtag from being saved:</h2>

      <ul>
        <% acorn_hashtag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :acorn_id, style: "display: block" %>
    <%= form.text_field :acorn_id %>
  </div>

  <div>
    <%= form.label :hastag_id, style: "display: block" %>
    <%= form.text_field :hastag_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/acorn_hashtags/edit.html.erb
<h1>Editing acorn hashtag</h1>

<%= render "form", acorn_hashtag: @acorn_hashtag %>

<br>

<div>
  <%= link_to "Show this acorn hashtag", @acorn_hashtag %> |
  <%= link_to "Back to acorn hashtags", acorn_hashtags_path %>
</div>

app/views/acorn_hashtags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Acorn hashtags</h1>

<div id="acorn_hashtags">
  <% @acorn_hashtags.each do |acorn_hashtag| %>
    <%= render acorn_hashtag %>
    <p>
      <%= link_to "Show this acorn hashtag", acorn_hashtag %>
    </p>
  <% end %>
</div>

<%= link_to "New acorn hashtag", new_acorn_hashtag_path %>

app/views/acorn_hashtags/new.html.erb
<h1>New acorn hashtag</h1>

<%= render "form", acorn_hashtag: @acorn_hashtag %>

<br>

<div>
  <%= link_to "Back to acorn hashtags", acorn_hashtags_path %>
</div>

app/views/acorn_hashtags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @acorn_hashtag %>

<div>
  <%= link_to "Edit this acorn hashtag", edit_acorn_hashtag_path(@acorn_hashtag) %> |
  <%= link_to "Back to acorn hashtags", acorn_hashtags_path %>

  <%= button_to "Destroy this acorn hashtag", @acorn_hashtag, method: :delete %>
</div>